name: CI

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  inspect-code:
    name: Inspect code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.18
      - name: Setup cache for Chromium binary
        uses: actions/cache@v3
        with:
          path: .local-chromium
          key: ${{ runner.os }}-chromium-${{ hashFiles('src/revisions.ts') }}
      - name: Install dependencies
        run: npm ci
      - name: Check code
        run: npm run check
      - name: Lint code
        run: npm run lint
      - name: Lint commits
        run: npm run commitlint

  tests:
    name: ${{ matrix.spec.name }} tests (${{ matrix.spec.node }})
    runs-on: ${{ matrix.spec.machine }}
    continue-on-error: true
    strategy:
      matrix:
        spec:
          - name: Linux
            machine: ubuntu-latest
            node: 14
          - name: Linux
            machine: ubuntu-latest
            node: 16
          - name: Linux
            machine: ubuntu-latest
            node: 18.18
          - name: macOS
            machine: macos-13
            node: 14
          - name: Windows
            machine: windows-latest
            node: 14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup cache for Chromium binary
        uses: actions/cache@v3
        with:
          path: .local-chromium
          key: ${{ runner.os }}-chromium-${{ hashFiles('src/revisions.ts') }}
      - name: Setup cache for Firefox binary
        uses: actions/cache@v3
        with:
          path: .local-firefox
          key: ${{ runner.os }}-firefox-${{ hashFiles('src/revisions.ts') }}
      - name: Set up Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.spec.node }}
      - name: Install dependencies with Chromium
        run: npm install
      - name: Install Firefox
        env:
          PUPPETEER_PRODUCT: firefox
        run: npm install
      - name: Install linux dependencies.
        if: ${{ matrix.spec.name == 'Linux' }}
        run: sudo apt-get install xvfb
      - name: Build
        run: npm run build
      - name: Test types
        run: npm run test:types
      # On Linux we run all Chrome tests without retries and Firefox tests with retries.
      - name: Run all Chrome tests (only on Linux)
        if: ${{ matrix.spec.name == 'Linux' }}
        run: xvfb-run --auto-servernum npm run test:chrome
      - name: Run all Firefox tests (only on Linux)
        if: ${{ matrix.spec.name == 'Linux' }}
        uses: nick-invision/retry@v3
        with:
          command: xvfb-run --auto-servernum npm run test:firefox
          timeout_minutes: 20
          max_attempts: 3
      # On other platforms we only run chrome:headless tests and continue on Firefox errors.
      - name: Test Chrome Headless (not on Linux)
        id: test-chrome
        if: ${{ matrix.spec.name != 'Linux' }}
        run: npm run test:chrome:headless
      - name: Run all Firefox tests (not on Linux)
        if: ${{ matrix.spec.name != 'Linux' }}
        continue-on-error: true
        run: npm run test:firefox
